FROM python:3.12-slim AS base

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV ROOT=/testing
ENV PYTHONPATH="3.11:/app/src/"

WORKDIR $ROOT

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential \
  && apt-get install -y --no-install-recommends apt-utils \
  && apt-get install -y --no-install-recommends libc-dev \
  && apt-get install -y --no-install-recommends gcc \
  && apt-get install -y --no-install-recommends gettext \
  && apt-get install -y --no-install-recommends screen \
  && apt-get install -y --no-install-recommends vim \
  && apt-get clean

ENV VIRTUALENV=$ROOT/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH=$VIRTUALENV/bin:$PATH

COPY constraints.txt pytest.ini $ROOT/
COPY src/tests/ $ROOT/tests/
COPY src/app/ $ROOT/app/

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r $ROOT/constraints.txt \
    && flake8 $ROOT/app/ --max-line-length 120

FROM python:3.12-slim
ENV ROOT=/testing
COPY --from=base $ROOT/venv $ROOT/venv
ENV PATH="$ROOT/venv/bin:$PATH"

COPY commands/ $ROOT/commands/
RUN chmod +x $ROOT/commands/*
ENV PATH="$ROOT/commands:$PATH"

ADD src $ROOT/src

WORKDIR $ROOT/src
CMD [ "start_dev.sh" ]
