version: "3.10"


x-common-variables: &common-variables
  POSTGRES_USER: db_user
  POSTGRES_PASSWORD: db_pass
  POSTGRES_DB: orders_db
  POSTGRES_PORT: 5432
  AUTH_URL: http://auth-service:8000/api/users
  REDIS_PORT: 6379
  REDIS_HOST: redis-service

services:
  redis-service:
    image: "redis:7.0.10-bullseye"
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"
    ports:
      - "6379:6379"

  db-service:
    image: postgres:15-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5431:5432"
    expose:
      - 5431
    environment: *common-variables
    networks:
      - backend-network

  web-service:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      <<: *common-variables
      PG_HOST: db-service
    ports:
      - "80:8000"
    networks:
      - backend-network
    depends_on:
      - db-service
      - redis-service
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  redis-volume:
